require 'rubygems'
require 'bundler/setup'
require 'fileutils'
require 'joyce'
require 'joyce/tasks/build'

task :app do
  Joyce::Tasks::AppBuilder.new.make({
    app_name: "joyce-example",
    app_class_name: 'Example::Application',
    template_location: "../dist/Ruby.app",
    target_directory: "../dist"
  })
end
